rule win_revil_auto {
 
    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2020-12-01"
        version = "1"
        description = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.5.0"
        tool_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.revil"
        malpedia_rule_date = "20201127"
        malpedia_hash = "ae61de407d8ec67cdbe44187237e174f42b42c47"
        malpedia_version = ""
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"
 
    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */
 
 
    strings:
        $sequence_0 = { 833d????????00 752f 6a00 6800001000 6a00 }
            // n = 5, score = 4200
            //   833d????????00       |                     
            //   752f                 | jne                 0x31
            //   6a00                 | push                0
            //   6800001000           | push                0x100000
            //   6a00                 | push                0
 
        $sequence_1 = { 50 57 ff15???????? 83c410 8bc7 }
            // n = 5, score = 4200
            //   50                   | push                eax
            //   57                   | push                edi
            //   ff15????????         |                     
            //   83c410               | add                 esp, 0x10
            //   8bc7                 | mov                 eax, edi
 
        $sequence_2 = { 894a58 8bce 89425c 33c0 8b9a88000000 8b928c000000 }
            // n = 6, score = 4200
            //   894a58               | mov                 dword ptr [edx + 0x58], ecx
            //   8bce                 | mov                 ecx, esi
            //   89425c               | mov                 dword ptr [edx + 0x5c], eax
            //   33c0                 | xor                 eax, eax
            //   8b9a88000000         | mov                 ebx, dword ptr [edx + 0x88]
            //   8b928c000000         | mov                 edx, dword ptr [edx + 0x8c]
 
        $sequence_3 = { 8d8510ffffff 50 8d8560ffffff 50 8d45b0 50 e8???????? }
            // n = 7, score = 4200
            //   8d8510ffffff         | lea                 eax, [ebp - 0xf0]
            //   50                   | push                eax
            //   8d8560ffffff         | lea                 eax, [ebp - 0xa0]
            //   50                   | push                eax
            //   8d45b0               | lea                 eax, [ebp - 0x50]
            //   50                   | push                eax
            //   e8????????           |                     
 
        $sequence_4 = { 743c 0fb71f 8bd7 6685db }
            // n = 4, score = 4200
            //   743c                 | je                  0x3e
            //   0fb71f               | movzx               ebx, word ptr [edi]
            //   8bd7                 | mov                 edx, edi
            //   6685db               | test                bx, bx
 
        $sequence_5 = { 745c ff750c e8???????? 8906 59 85c0 7427 }
            // n = 7, score = 4200
            //   745c                 | je                  0x5e
            //   ff750c               | push                dword ptr [ebp + 0xc]
            //   e8????????           |                     
            //   8906                 | mov                 dword ptr [esi], eax
            //   59                   | pop                 ecx
            //   85c0                 | test                eax, eax
            //   7427                 | je                  0x29
 
        $sequence_6 = { 8b7df8 85ff 7749 7205 83f9ff 7742 85d2 }
            // n = 7, score = 4200
            //   8b7df8               | mov                 edi, dword ptr [ebp - 8]
            //   85ff                 | test                edi, edi
            //   7749                 | ja                  0x4b
            //   7205                 | jb                  7
            //   83f9ff               | cmp                 ecx, -1
            //   7742                 | ja                  0x44
            //   85d2                 | test                edx, edx
 
        $sequence_7 = { 8365fc00 8d45fc 56 50 8d450c 50 }
            // n = 6, score = 4200
            //   8365fc00             | and                 dword ptr [ebp - 4], 0
            //   8d45fc               | lea                 eax, [ebp - 4]
            //   56                   | push                esi
            //   50                   | push                eax
            //   8d450c               | lea                 eax, [ebp + 0xc]
            //   50                   | push                eax
 
        $sequence_8 = { c3 0fbec0 83f861 7f10 740a 83e841 }
            // n = 6, score = 4200
            //   c3                   | ret                 
            //   0fbec0               | movsx               eax, al
            //   83f861               | cmp                 eax, 0x61
            //   7f10                 | jg                  0x12
            //   740a                 | je                  0xc
            //   83e841               | sub                 eax, 0x41
 
        $sequence_9 = { 8b7d08 57 e8???????? 59 59 85c0 7407 }
            // n = 7, score = 4200
            //   8b7d08               | mov                 edi, dword ptr [ebp + 8]
            //   57                   | push                edi
            //   e8????????           |                     
            //   59                   | pop                 ecx
            //   59                   | pop                 ecx
            //   85c0                 | test                eax, eax
            //   7407                 | je                  9
 
    condition:
        7 of them and filesize < 155794432
}
